version: '3.8'

services:
  app:
    build: ./php
    container_name: php_cms_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    env_file:
      - ./secrets.env
    depends_on:
      - db
    networks:
      - cms-net

  web:
    image: nginx:stable-alpine
    container_name: php_cms_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - cms-net

  db:
    image: mysql:8.0
    container_name: php_cms_db
    restart: unless-stopped
    env_file:
      - ./secrets.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - cms-net

  adminer:
    image: adminer
    container_name: php_cms_adminer
    ports:
      - "8081:8080"
    networks:
      - cms-net

volumes:
  db_data: {}

networks:
  cms-net:
    driver: bridge
